
warn = [
    "clippy::unwrap_used",
    "clippy::expect_used",

    "clippy::clone_on_copy",
    "clippy::clone_on_ref_ptr",

    "clippy::panic",
    "clippy::todo",
    "clippy::unimplemented",
    "clippy::unreachable",

    "clippy::inefficient_to_string",
    "clippy::unnecessary_clone",
    "clippy::redundant_clone",

    "clippy::result_unit_err",
    "clippy::map_unwrap_or",

    "clippy::needless_borrow",
    "clippy::needless_return",
    "clippy::redundant_pattern_matching",
]

allow = [
    "clippy::too_many_arguments",
    "clippy::type_complexity",
    "clippy::large_enum_variant",
    "clippy::module_inception",
]
